// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using WatchKit;

namespace hearRINGWatchOS.WatchOSApp
{
	public partial class InterfaceController : WKInterfaceController
	{
		public InterfaceController (IntPtr handle) : base (handle)
		{
		}
	}
}
