 version: '3.7'
 services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/home/node/app
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - "1337:1337"

  webpack:
    container_name: webpack
    build: .
    depends_on:
      - web
    volumes_from:
      - web
    working_dir: /home/node/app
    command: npm run dev
    ports: 
      - "8080:8080"